app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('web.index');
    //echo "this is warmup only";
    //return view('welcome');
});

//return the getAbout function in pagesController
//'as' is for naming the route
Route::get('about', [
    'as' => 'about',
    'uses' => 'pagesController@getAbout'
]);

//return the getLogin function in pagesController
Route::get('login', [
    'as' => 'login',
    'uses' => 'pagesController@getLogin'
]);

//routing of the test page
Route::get('test', [
    'as' => 'test',
    'uses' => 'pagesController@getTest'
]);

//routing of the test2 page
//also get the data from the Product model
Route::get('test2', ['as' => 'test2', function(){
    $data = App\Product::all();
    return view('pages.test2') -> withData($data);
}]);

//Routing for edit button in test2
Route::post ( '/editItem', function (Request $request) {

    $rules = array (
        'name' => 'required|alpha',
        'price' => 'required'
    );
    $validator = Validator::make ( Input::all (), $rules );
    if ($validator->fails ())
        return Response::json ( array (
            'errors' => $validator->getMessageBag ()->toArray ()
        ) );
    else {

        $data = Data::find ( $request->id );
        $data->name = ($request->name);
        $data->price = ($request->price);
        $data->save ();
        return response ()->json ( $data );
    }
} );

//routing of the signin/signup view
Route::get ( 'customAuth', function () {
    return view ( 'customAuthentication' );
} );
Route::post ( '/login', 'MainController@login' );
Route::post ( '/register', 'MainController@register' );
Route::get ( '/logout', 'MainController@logout' );

//routing of the product view
Route::resource('product', 'productController');

//routing of the fletching of data to DataTables
Route::get('/serverSide', [
    'as'   => 'serverSide',
    'uses' => function () {
        $users = App\Product::all(); //

//        return $users;
        return Datatables::of($users)->make();
    }
]);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamps = false;

    protected $table = 'products'; // products is the name of the table in database

    protected $fillable = ['name'];
}

app/Http/Controllers/productController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Symfony\Component\DomCrawler\Form;

class productController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all(); //all() is the eloquent function to retrieve all the data in Product
       // return $products;


//        return $products;

       return view("products.index") -> with("products", $products); //return the view of the database

        //return 'This is the index page of product'; //testing purpose

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("products.create"); //return the view of creating of products
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this -> validate($request, [
            'name' => 'required',
            'price' => 'required'
        ]); //validation process

        $product = new Product; //Product is the model
        $product->name = $request->name;
        $product->price = $request->price;
        $product->save(); //to save the product to the database

        //return "Something"; //for testing purpose

        //return redirect()->route('product.index'); // one way to redirect to product.index page

        return redirect()->action('productController@index');//another way to redirect using action
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //return $id; //testing only

        $product = Product::find($id); //retrieve a single product with that id

        //return $product;  //return the data

        return view("products.show")->with('products', $product); //return the view of show

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        //$product = Product::where('id', $id) -> first(); //another way to retrieve a data with that id

       // return $product;

        return view('products.edit', compact('product', $product)); //return the edit view of the product
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this -> validate($request, [
            'name' => 'required',
            'price' => 'required'
        ]); //validation process

        $product = Product::find($id);

        $product->name = $request->name;
        $product->price = $request->price;

        $product->save();

        return redirect() -> route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Product::destroy($id); //destroy method

        $product = Product::find($id)
            ->delete(); //delete method, another way to do the same thing

        return redirect()->route('product.index');
    }
}

resources/views/products/create.blade.php
@extends('layout.layout')

@section('title')
    Create new product
@stop

@section('content')

    <h1>Create a new product</h1>

{!! Form::open (['route'=>'product.store']) !!}

{!! Form::label('name', 'Name') !!}
{!! Form::text('name') !!}
{!! Form::label('price', 'Price') !!}
{!! Form::text('price') !!}

{!! Form::submit('Create') !!}

{!! Form::close() !!}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


@stop

resources/views/products/edit.blade.php
@extends('layout.layout')

@section('title')
    Edit product: {{$product->name}}
@stop

@section('content')

    {!! Form::model ($product,
        [
        'method'=>'patch',
        'route'=>['product.update', $product->id]
        ]
        ) !!}

    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', $product->name) !!}

    <br>

    {!! Form::label('price', 'Price') !!}
    {!! Form::text('price', $product->price) !!}

    {!! Form::submit('Edit') !!}

    {!! Form::close() !!}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

@stop

resources/views/products/index.blade.php
@extends('layout.layout')

@section('title')
    All Products
@stop

@section('header')
    <link
            href="https://cdn.datatables.net/1.10.12/css/dataTables.material.min.css"
            rel="stylesheet">
    <link
            href="//cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css"
            rel="stylesheet">

    <link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">

    <style>
        tfoot input {
            width: 100%;
            padding: 3px;
            box-sizing: border-box;
        }
    </style>
@stop


@section('content')

    <table id="example" class="datatable mdl-data-table dataTable" cellspacing="0"
           width="100%" role="grid"
           style="width: 100%;">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Product</th>
        </tr>
        <tfoot>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Product</th>
        </tr>
        </tfoot>
        </thead>
        <tbody>
        </tbody>
    </table>

    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.material.min.js"></script>

    <script src="//code.jquery.com/jquery-1.12.3.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>


    <script>
/*        //initialize the data table
        $(document).ready(function(){

            $('#example').DataTable({
                processing: true,
                serverSide: true, //it calls route to serverSide, so check if the route is created in routes.php
                ajax: '{{ route('serverSide') }}',
                columnDefs: [
                    {
                        targets: [ 0, 1, 2 ],
                        className: 'mdl-data-table__cell--non-numeric'
                    }
                ]
            });
        });*/

        //column searching by text
        $(document).ready(function() {
            // Setup - add a text input to each footer cell, careful if there is footer in the table
            $('#example tfoot th').each( function () {
                var title = $(this).text();
                $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
            } );
            // initialize the data table from serverSide
            var table = $('#example').DataTable({
                processing: true,
                serverSide: true, //it calls route to serverSide, so check if the route is created in routes.php
                ajax: '{{ route('serverSide') }}',
                    });
            // Apply the search
            table.columns().every( function () {
                var that = this;

                $( 'input', this.footer() ).on( 'keyup change', function () {
                    if ( that.search() !== this.value ) {
                        that
                                .search( this.value )
                                .draw();
                    }
                } );
            } );
        } );
    </script>

   <h1>testing for translation: {{trans('main.main')}}</h1>

   <h1><a href="{{route('product.create')}}">Create a new product</a></h1>

    @foreach($products as $product)

        <h1>no. {{$product -> id}}</h1>
        <h1>Name: {{$product -> name}}</h1>
        <h1>Price: {{$product -> price}}</h1>

        <h1><a href="{{route('product.show', $product->id)}}">Check this product</a></h1>

        <br>

    @endforeach



@stop

resources/views/products/show.blade.php
@extends('layout.layout')

@section('title')
    {{$products->name}}
@stop

@section('content')

    {!!Form::open(
        [
        'method'=>'delete',
        'route'=>['product.destroy', $products->id]
        ]
        )!!}

    <h1>Name: {{$products->name}}</h1>
    <h1>Price: {{$products->price}}</h1>

    <a href="{{route('product.edit', $products->id)}}">Edit</a>

    <br>

    {!!Form::submit('Delete')!!}

    {!!Form::close()!!}

@stop